config/routes.rb
Pinteresting::Application.routes.draw do
  resources :notes

  resources :advertisers

  devise_for :users
  
  root "advertisers#index"
  get "about" => "pages#about"
  get "weekly_progress" => "pages#weekly_progress"
  get "summary" => "summary#index"
  get "yesterday" => "pages#yesterday"
  get "by_week" => "pages#by_week"
  get "this_month" => "pages#this_month"
  get "all" => "pages#all"
  get "opps" => "pages#opps"
  get "finished" => "pages#finished"
  get "_all" => "pages#_all"

  

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def correct_user
      @advertiser = current_user.notes.find_by(id: params[:id])
      redirect_to advertisers_path, notice: "Sorry, that action is not allowed" if @advertiser.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :note, :tag)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class ="row">
<div class = "col-xs-12 col-md-6">
   <div class="field">
    <%= f.text_field :title, class: "form-control", placeholder: "Title"%></br>
  </div></div>
  <div class = "col-xs-12 col-md-6">
  <div class="field">
    <%= f.text_field :tag, class: "form-control", placeholder: "Tags (Separate by Commas)"%></br>
  </div></div></div>
  <div class="textarea">
        <%= f.text_area :note, class: "form-control", rows: 20, placeholder: "Begin Note..." %><br></div>
  <div class="actions">
    <%= f.submit "Update Note", class: "btn btn-danger btn-lg" %>
  </div>
<% end %>

app/views/notes/_formnew.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class ="row">
<div class = "col-xs-12 col-md-6">
   <div class="field">
    <%= f.text_field :title, class: "form-control", placeholder: "Title"%></br>
  </div></div>
  <div class = "col-xs-12 col-md-6">
  <div class="field">
    <%= f.text_field :tag, class: "form-control", placeholder: "Tags (Separate by Commas)"%></br>
  </div></div></div>
  <div class="textarea">
        <%= f.text_area :note, class: "form-control", rows: 20, placeholder: "Begin Note..." %><br></div>
        <div class="actions">
    <%= f.submit "+ Note", class: "btn btn-info btn-lg" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading">
	<h1>Editing Note: <%= @note.title%></h1>
</div>
<div class="panel-body">
	<%= render 'form' %>
</div>
<div class = "panel-footer">
	<%= link_to 'Show Note', @note %> |
<%= link_to 'Back to Notes', notes_path %>
</div>
</div>

app/views/notes/index.html.erb
<% if user_signed_in? %>
  <div class = "panel panel-default">
        <div class = "panel-heading">
          <h1>My Notes: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'New Note', new_note_path, class: "btn btn-default btn-lg" %>
</h1>
</div>


        <div class ="panel-body">
          <table class="table table-hover">
            <thead>
             <tr><strong>
                <th>Title</th>
                <th>Description</th>
                <th></th>
                 <th></th>
                 <th></th>
                 <th></th></strong>
              </tr>
            </thead>
          <tbody>
            <% @notes.each do |note| %>
            <% if note.user == current_user %>
              <tr>
                <td><strong><%= note.title %></strong></td>
                <td><%= note.note[0,170] %>...</td>
                <td></td>
                <td><%= link_to 'Edit', edit_note_path(note), class: "btn btn-info" %></td>
                <td><%= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure you want to delete this note?' }, class: "btn btn-danger" %></td>
              </tr>
              <% end %><% end %>
          </tbody>
        </table>
      </div>
        </br>
        <div class= "panel-footer">
          <%= link_to 'New Note', new_note_path, class: "btn btn-info btn-lg" %>
        </div>
      </div>
  <% else %>
  <div class="jumbotron center">
       <h1>Sign in to continue...</h1>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      </p>    
<% end %>

  

app/views/notes/new.html.erb
<div class = "panel panel-default">
	<div class = "panel-heading">
		<h1>New Note</h1>
	</div>
	<div class = "panel-body">
		<%= render 'formnew' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Back to Notes', notes_path %>
	</div>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "panel panel-default">
  <div class = "panel-heading">
    <h1><% @note.title %></h1>
  </div>
  <div class = "panel-body">
    <div class = "form-group">
  <SPAN ID="copytext"> 
      <p>
  <strong>Note:</strong>
  <%= @note.note %>
</p>

<p>
  <strong>Tag(s):</strong>
  <%= @note.tag %>
</p>

    </SPAN>
  </div></div>
  <div class = "panel-footer">
    <%= link_to 'Edit', edit_note_path(@advertiser) %> |
    <%= link_to 'Back to Cases', notes_path %>
  </div></div>

  