config/routes.rb
Pinteresting::Application.routes.draw do
  resources :notes

  resources :advertisers

  devise_for :users
  
  root "advertisers#index"
  get "about" => "pages#about"
  get "weekly_progress" => "pages#weekly_progress"
  get "summary" => "summary#index"
  get "yesterday" => "pages#yesterday"
  get "by_week" => "pages#by_week"
  get "this_month" => "pages#this_month"
  get "all" => "pages#all"
  get "opps" => "pages#opps"
  get "finished" => "pages#finished"
  get "_all" => "pages#_all"

  

end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
	belongs_to :user

	def self.to_csv
  		CSV.generate do |csv|
			csv << column_names
			all.each do |advertiser|
				csv << advertiser.attributes.values_at(*column_names)
			end
		end
	end
end

app/controllers/advertisers_controller.rb
class AdvertisersController < ApplicationController
  
  before_action :set_advertiser, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /advertisers
  # GET /advertisers.json
  def index
    @advertisers = current_user.advertisers.today
    respond_to do |format|
      format.html
      format.csv { send_data @advertisers.to_csv }
    end
  end

  # GET /advertisers/1
  # GET /advertisers/1.json
  def show
  end


  # GET /advertisers/new
  def new
    @advertiser = current_user.advertisers.build
    
  end


  # GET /advertisers/1/edit
  def edit
  end

  # POST /advertisers
  # POST /advertisers.json
  def create
    @advertiser = current_user.advertisers.build(advertiser_params)

    respond_to do |format|
      if @advertiser.save
        format.html { redirect_to @advertiser }
        format.json { render action: 'show', status: :created, location: @advertiser }
      else
        format.html { render action: 'new' }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisers/1
  # PATCH/PUT /advertisers/1.json
  def update
    respond_to do |format|
      if @advertiser.update(advertiser_params)
        format.html { redirect_to advertiser_path}
        format.json { head :no_content }
        
      else
        format.html { render action: 'edit' }
        format.json { render json: @advertiser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisers/1
  # DELETE /advertisers/1.json
  def destroy
    @advertiser.destroy
    respond_to do |format|
      format.html { redirect_to advertisers_url }
      format.json { head :no_content }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertiser
      @advertiser = Advertiser.find(params[:id])
    end

    def correct_user
      @advertiser = current_user.advertisers.find_by(id: params[:id])
      redirect_to advertisers_path, notice: "That action is not allowed" if @advertiser.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertiser_params
      params.require(:advertiser).permit(:name, :security, :cid, :issue, :points, :finished, :created_at)
    end
end

app/helpers/advertisers_helper.rb
module AdvertisersHelper
end

app/views/advertisers/_form.html.erb
<script type="text/javascript">
    mixpanel.track_forms("f.submit", "Update Case", {
        "referrer": document.referrer
    });
</script>

<%= form_for(@advertiser) do |f| %>
  <% if @advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% @advertiser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="field">
    <%= f.text_field :name, class: "form-control", placeholder: "Name"%></br></div>
    <div class = "row">
  <div class "field">
    <div class = "col-xs-12 col-md-3">
    <%= f.text_field :security, class: "form-control", placeholder: "Security Checked?" %></br>
  </div></div>
  <div class="col-xs-12 col-md-3">
    <div class = "field">
    <%= f.number_field :cid, class: "form-control", placeholder: "CID Number"%></br>
  </div></div>
  <div class = "col-xs-12 col-md-3">
  <div class="field">
    <%= f.number_field :points, class: "form-control", placeholder: "How many points?" %></br>
  </div></div>
   <div class = "col-xs-12 col-md-3">
  <div class="field">
    <%= f.text_field :finished, class: "form-control", placeholder: "Finished?" %></br>
  </div></div>
</div>
  <div class="textarea">
        <%= f.text_area :issue, class: "form-control",rows:15, :value => "1. Describe the root cause of the issue (diagnostic)? Be very specific about the UI element / feature (“AdWords Billing” is too generic)*
PLEASE DO NOT ENTER PERSONAL INFORMATION (go/whatispii)




2. How did you resolve the query?*



3. Other comments(Optional)" %></p><br></div>
  <div class="actions">
    <%= f.submit "Update Case", class: "btn btn-warning btn-lg" %>
  </div>
<% end %>

app/views/advertisers/_formnew.html.erb
<%= form_for(@advertiser) do |f| %>
  <% if @advertiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertiser.errors.count, "error") %> prohibited this advertiser from being saved:</h2>

      <ul>
      <% @advertiser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="field">
    <%= f.text_field :name, class: "form-control", placeholder: "Name"%></br></div>
    <div class = "row">
  <div class "field">
    <div class = "col-xs-12 col-md-3">
    <%= f.text_field :security, class: "form-control", placeholder: "Security Checked?" %></br>
  </div></div>
  <div class="col-xs-12 col-md-3">
    <div class = "field">
    <%= f.number_field :cid, class: "form-control", placeholder: "CID Number"%></br>
  </div></div>
  <div class = "col-xs-12 col-md-3">
  <div class="field">
    <%= f.number_field :points, class: "form-control", placeholder: "94/7/11 YO" %></br>
  </div></div>
  <div class = "col-xs-12 col-md-3">
  <div class="field">
    <%= f.text_field :finished, class: "form-control", placeholder: "Finished?" %></br>
  </div></div>
</div>
      <div class="textarea">
        <%= f.text_area :issue, class: "form-control", rows:15, :value => "1. Describe the root cause of the issue (diagnostic)?*



2. How did you resolve the query?*" %><br></div>
  <div class="actions">
    <%= f.submit "+ Case", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/advertisers/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading">
	<h1>Editing Case: <%= @advertiser.cid%></h1>
</div>
<div class="panel-body">
	<%= render 'form' %>
</div>
<div class = "panel-footer">
	<%= link_to 'Show Case', @advertiser %> |
<%= link_to 'Back to Cases', advertisers_path %>
</div>
</div>

app/views/advertisers/index.html.erb
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">



  <% if user_signed_in? %><% x = 0 %>
    <% @advertisers.each do |advertiser| %>
            <% if advertiser.user == current_user %>
             <% x +=1 %>
             <% end %><% end %>

    <div class = "panel panel-default">
        <div class = "panel-heading">
          <div class = "row">
              <div class = "col-xs-12 col-md-8">
                <h1>Today's Cases: <%= x %></h1></div>


            <div class = "col-xs-12 col-md-4" align="right">
                
                   <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">Change Date Range<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li align = "center"><%= link_to "View Yesterday", yesterday_path %></li>
                      <li align = "center"><%= link_to "View This Week" , by_week_path %></li>
                      <li align = "center"><%= link_to "View This Month" , this_month_path %></li>
                      <li align = "center"><%= link_to "View All Time" , all_path %></li>
                    </ul>-->&nbsp;&nbsp;&nbsp;&nbsp;
                    <%= link_to '+ New Case', new_advertiser_path, class: "btn btn-default btn-lg" %>
                  </div></div>
</div>
        <div class ="panel-body">
          <table class="table table-hover">
            <thead>
             <tr>
                <th>Name</th>
                <th>Security</th>
                <th>CID</th>
                <th>Case Description</th>
                <th>Finished?</th>
                <th>View</th>
                <th>Delete</th>
              </tr>
            </thead>
          <tbody>
        <% @advertisers.each do |advertiser| %>
            <% if advertiser.user == current_user %>
              <tr>
                <td><%= advertiser.name %></td>
                <td><% if (advertiser.security == "yes") %>
                      <span class="label label-success">
                        <%= advertiser.security %></span>
                      </td>
                    <% else %>
                      <span class="label label-danger">
                        <%= advertiser.security %></span>
                      </td>
                  <% end %>
                <td><%= advertiser.cid %></td>
                <td><%= advertiser.issue %></td>
                <!--<td>
                  <% if (advertiser.points == 5) %>
                    <span class = "label label-danger">
                      <%= advertiser.points %></span>
                    </td>
                    <% elsif (advertiser.points == 12) %>
                    <span class = "label label-warning">
                      <%= advertiser.points %></span>
                    </td>
                    <% elsif (advertiser.points == 20) %>
                    <span class = "label label-info">
                      <%= advertiser.points %></span>
                    </td>
                  <% else %>
                    <span class = "label label-success">
                      <%= advertiser.points %></span>
                  <% end %>-->
                  
                  <td>
                    <% if (advertiser.finished == "yes") %>
                      <span class="label label-success">
                        <%= advertiser.finished %></span>
                      </td>
                    <% else %>
                      <span class="label label-danger" data-toggle="modal" data-target="#myModal">
                        <%= advertiser.finished %></span>
                              <% end %>
                              </td>
                <td class="col-md-1"><%= link_to 'Case Card', advertiser, class: "btn btn-warning" %></td>
                <td class="col-md-1"><%= link_to 'Delete' , advertiser, method: :delete, data: { confirm: 'Are you sure you want to delete this case from your records?' }, class: "btn btn-danger " %></td>
              </tr>
            <% end %>

          <% end %>
          </tbody>
        </table>
      </div>
        </br>
        <div class= "panel-footer">
          <%= link_to 'New Case', new_advertiser_path, class: "btn btn-success btn-lg" %>
        </div>
      </div>
  <% else %>
  <div class="jumbotron center">
       <h1>Sign in to continue...</h1>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      </p>    
<% end %>

app/views/advertisers/new.html.erb
<div class = "panel panel-default">
	<div class = "panel-heading">
		<h1>New Case</h1>
	</div>
<div class = "panel-body">
	<%= render 'formnew' %>
</div>
<div class="panel-footer">
	<%= link_to 'Back to Cases', advertisers_path %>
</div>
</div>

app/views/advertisers/show.html.erb
<script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#d_clip_button"))
  });

  $("#clear-test").on("click", function(){
    $("#fe_text").val("Copy me!");
    $("#testarea").val("");
  });
</script>


<p id="notice"><%= notice %></p>
<div class = "panel panel-default">
  <div class = "panel-heading">
    <div class ="row">
     <div class = "col-xs-12 col-md-9">
    <h1>Case Card for CID: <%= @advertiser.cid %></h1>
      </div>
    <div class = "col-xs-12 col-md-3">
    </div></div>
  </div>
  <div class = "panel-body">
    <div class = "form-group" > 
        <p>
      <strong>Name:</strong>
        <%= @advertiser.name%>
      </p>

      <p>
        <strong>Security:</strong>
        <%= @advertiser.security %>
      </p>

      <p>
        <strong>Cid:</strong>
        <%= @advertiser.cid %>
      </p>

      <p>
        <strong>Issue:</strong>
        <%= @advertiser.issue %>
      </p>

      <p>
        <strong>Pitch:</strong>
        <%= @advertiser.points %>
      </p>

      <p><strong>Follow Up Required:</strong></p>
    </br><!--<button class='btn btn-primary btn-lg' data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button' title='Copy Phone Note'>
    <b>Copy Phone Note</b>
  </button>-->
  </div></div>
  <div class = "panel-footer">
    <%= link_to 'Edit', edit_advertiser_path(@advertiser) %> |
    <%= link_to 'Back to Cases', advertisers_path %>
  </div></div>
  

app/views/advertisers/yesterday.html.erb
  <% if user_signed_in? %><% x = 0 %>
    <% @advertisers.each do |advertiser| %>
            <% if advertiser.user == current_user %>
             <% x +=1 %>
             <% end %><% end %>

    <div class = "panel panel-default">
        <div class = "panel-heading">
          <h1>Listing Cases: <%= x %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'New Case', new_advertiser_path, class: "btn btn-default btn-lg" %>
</div>
        
        <div class ="panel-body">
          <table class="table table-hover">
            <thead>
             <tr>
                <th>Name</th>
                <th>Security</th>
                <th>CID</th>
                <th>Issue</th>
                <th>Points</th>
                <th>View</th>
                <th>Delete</th>
              </tr>
            </thead>
          <tbody>
  
        <% @advertisers.each do |advertiser| %>
        <% if Advertiser.yesterday %>
            <% if advertiser.user == current_user %>
              <tr>
                <td><%= advertiser.name %></td>
                <td><% if (advertiser.security == "yes") %>
                      <span class="label label-success">
                        <%= advertiser.security %></span>
                      </td>
                    <% else %>
                      <span class="label label-danger">
                        <%= advertiser.security %></span>
                      </td>
                  <% end %>
                <td><%= advertiser.cid %></td>
                <td><%= advertiser.issue %></td>
                <td>
                  <% if (advertiser.points == 5) %>
                    <span class = "label label-danger">
                      <%= advertiser.points %></span>
                    </td>
                    <% elsif (advertiser.points == 12) %>
                    <span class = "label label-warning">
                      <%= advertiser.points %></span>
                    </td>
                    <% elsif (advertiser.points == 20) %>
                    <span class = "label label-info">
                      <%= advertiser.points %></span>
                    </td>
                  <% else %>
                    <span class = "label label-success">
                      <%= advertiser.points %></span>
                  <% end %>
                  </td>
                <td class="col-md-1"><%= link_to 'Case Card', advertiser, class: "btn btn-warning" %></td>
                <td class="col-md-1"><%= link_to 'Delete', advertiser, method: :delete, data: { confirm: 'Are you sure you want to delete this case from your records?' }, class: "btn btn-danger" %></td>
              </tr>
            <% end %>
          <% end %><% end %>
          </tbody>
        </table>
      </div>
        </br>
        <div class= "panel-footer">
          <%= link_to 'New Case', new_advertiser_path, class: "btn btn-success btn-lg" %>
        </div>
      </div>
  <% else %>
  <div class="jumbotron center">
       <h1>Sign in to continue...</h1>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      </p>    
<% end %>

  