config/routes.rb
Pinteresting::Application.routes.draw do
  resources :notes

  resources :advertisers

  devise_for :users
  
  root "advertisers#index"
  get "about" => "pages#about"
  get "weekly_progress" => "pages#weekly_progress"
  get "summary" => "summary#index"
  get "yesterday" => "pages#yesterday"
  get "by_week" => "pages#by_week"
  get "this_month" => "pages#this_month"
  get "all" => "pages#all"
  get "opps" => "pages#opps"
  get "finished" => "pages#finished"
  get "_all" => "pages#_all"

  

end

app/views/layouts/_header.html.erb
<!--<nav class="navbar navbar-default" role="navigation"> -->
  <!-- Brand and toggle get grouped for better mobile display -->
 
 <nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
 <a href = "../advertisers" class= "navbar-brand"><!--<img src ="https://signmax.us/achatenligne/logos/Images/Trex-5-24-2013.jpg" height = "30"/>&nbsp;&nbsp;<a href = "../advertisers" class= "navbar-brand"><img src ="https://www.google.com/images/srpr/logo11w.png" height = "25"/>&nbsp;&nbsp;-->Pitchzilla</a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <%if user_signed_in? %>
      <!--<li><%= link_to "+ Feedback", about_path %></li> -->
      <!--<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cases<b class="caret"></b></a>
        <ul class="dropdown-menu">-->
          
          <!--<li></span><%= link_to "+My Cases" , advertisers_path %></li>-->
          <!--<li><%= link_to "My Notes" , notes_path %></li> -->
          <!--<li><%= link_to "Check Assigned" , finished_path %></li> -->
          <!--<li><%= link_to "Find Opportunities" , opps_path %></li> -->
          <li style="color:green"> 94/7/11</li>
          <li><%= link_to "+NEW CASE", new_advertiser_path %></li>
           <li><%= link_to "Download", all_path(format: "csv") %></li>

        <!--</ul>-->
      
      <!--<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
        <ul class="dropdown-menu">-->
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

        <!--</ul>-->
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li> 
      <%end%>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pitchzilla</title>
  <link rel="icon" type="image/png" href="http://www.hamovhotov.com/icon/download/fasticon/dinosaurs-toys/tyrannosaurus-rex-256x256.png" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45865820-1', 'pitchzilla.herokuapp.com');
  ga('send', 'pageview');

</script>
</head>
<body>

<%=render 'layouts/header'%>
<div class ="container">
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
    <%= yield %>
</div>
<script type="text/javascript">
</script>
</body>
</html>